import type {
  RoleBasedTask,
  TaskActivity,
  ProjectScope,
  TaskRoomGroup,
  SpecialTaskGroup,
} from "../types/role-tasks";

// Mock rooms for grouping
export const MOCK_TASK_ROOMS = [
  { id: "room-1", name: "Living Room" },
  { id: "room-2", name: "Master Bedroom" },
  { id: "room-3", name: "Bedroom 2" },
  { id: "room-4", name: "Kitchen" },
  { id: "room-5", name: "Dining Area" },
  { id: "room-6", name: "Home Theater" },
  { id: "room-7", name: "Foyer" },
  { id: "room-8", name: "Balcony" },
];

// Project scope mock
export const MOCK_PROJECT_SCOPE: ProjectScope = {
  projectId: "proj-001",
  includesAutomation: true,
  includesAV: true,
  includesSecurity: true,
  includesLighting: true,
  includesHVAC: true,
};

const now = new Date().toISOString();
const yesterday = new Date(Date.now() - 86400000).toISOString();
const twoDaysAgo = new Date(Date.now() - 172800000).toISOString();

// PM Tasks - Focus on coordination and unblocking
export const MOCK_PM_TASKS: RoleBasedTask[] = [
  {
    id: "pm-task-001",
    projectId: "proj-001",
    title: "Get electrical layout approval from architect",
    description: "Need architect sign-off on revised DB panel placement",
    stakeholder: "SITE_SUPERVISOR",
    status: "IN_PROGRESS",
    priority: "HIGH",
    createdFrom: "MANUAL",
    createdAt: twoDaysAgo,
    updatedAt: yesterday,
    roleCategory: "PM",
    dependencyType: "ARCHITECT",
    dependencyNote: "Awaiting response from architect team",
  },
  {
    id: "pm-task-002",
    projectId: "proj-001",
    title: "Client approval for AV equipment placement",
    description: "Confirm speaker and display locations with client",
    stakeholder: "SITE_SUPERVISOR",
    status: "NOT_STARTED",
    priority: "HIGH",
    createdFrom: "MANUAL",
    createdAt: yesterday,
    updatedAt: yesterday,
    roleCategory: "PM",
    dependencyType: "CLIENT",
    dependencyNote: "Schedule site visit with client",
  },
  {
    id: "pm-task-003",
    projectId: "proj-001",
    title: "Coordinate HVAC ducting with contractor",
    description: "Third party HVAC contractor needs access schedule",
    stakeholder: "SITE_SUPERVISOR",
    status: "BLOCKED",
    priority: "MEDIUM",
    createdFrom: "MANUAL",
    createdAt: twoDaysAgo,
    updatedAt: now,
    roleCategory: "PM",
    dependencyType: "THIRD_PARTY",
    dependencyNote: "HVAC contractor delayed by 3 days",
    flagged: true,
    flagReason: "Critical path impact",
  },
  {
    id: "pm-task-004",
    projectId: "proj-001",
    title: "Order additional Cat6 cables",
    description: "Site survey revealed need for 2 more cable boxes",
    stakeholder: "STORE",
    status: "DONE",
    priority: "MEDIUM",
    createdFrom: "MANUAL",
    createdAt: twoDaysAgo,
    updatedAt: yesterday,
    roleCategory: "PM",
    dependencyType: "NONE",
  },
  {
    id: "pm-task-005",
    projectId: "proj-001",
    title: "Schedule pre-wire inspection",
    description: "Arrange for electrical inspector visit",
    stakeholder: "SITE_SUPERVISOR",
    status: "NOT_STARTED",
    priority: "HIGH",
    createdFrom: "MANUAL",
    createdAt: now,
    updatedAt: now,
    roleCategory: "PM",
    dependencyType: "THIRD_PARTY",
  },
  {
    id: "pm-task-006",
    projectId: "proj-001",
    title: "Confirm lighting scene requirements",
    description: "Get final scene list from interior designer",
    stakeholder: "DESIGNER",
    status: "IN_PROGRESS",
    priority: "MEDIUM",
    createdFrom: "MANUAL",
    createdAt: yesterday,
    updatedAt: now,
    roleCategory: "PM",
    dependencyType: "ARCHITECT",
  },
  {
    id: "pm-task-007",
    projectId: "proj-001",
    title: "Review and approve site photos",
    description: "Weekly site documentation review",
    stakeholder: "SITE_SUPERVISOR",
    status: "NOT_STARTED",
    priority: "LOW",
    createdFrom: "MANUAL",
    createdAt: now,
    updatedAt: now,
    roleCategory: "PM",
    dependencyType: "NONE",
  },
  {
    id: "pm-task-008",
    projectId: "proj-001",
    title: "Get client sign-off on automation scope",
    description: "Final confirmation on smart home features",
    stakeholder: "CLIENT",
    status: "IN_PROGRESS",
    priority: "HIGH",
    createdFrom: "MANUAL",
    createdAt: twoDaysAgo,
    updatedAt: yesterday,
    roleCategory: "PM",
    dependencyType: "CLIENT",
  },
];

// Installer Tasks - Derived from BOQ
export const MOCK_INSTALLER_TASKS: RoleBasedTask[] = [
  // Living Room tasks
  {
    id: "inst-task-001",
    projectId: "proj-001",
    title: "Install in-ceiling speakers (2 units)",
    description: "Mount and wire ceiling speakers per layout",
    stakeholder: "INSTALLER",
    status: "IN_PROGRESS",
    priority: "HIGH",
    createdFrom: "TEMPLATE",
    createdAt: twoDaysAgo,
    updatedAt: yesterday,
    roleCategory: "INSTALLER",
    roomId: "room-1",
  },
  {
    id: "inst-task-002",
    projectId: "proj-001",
    title: "Install WiFi access point",
    description: "Mount AP at designated ceiling location",
    stakeholder: "INSTALLER",
    status: "NOT_STARTED",
    priority: "MEDIUM",
    createdFrom: "TEMPLATE",
    createdAt: yesterday,
    updatedAt: yesterday,
    roleCategory: "INSTALLER",
    roomId: "room-1",
  },
  // Master Bedroom tasks
  {
    id: "inst-task-003",
    projectId: "proj-001",
    title: "Install curtain motors (2 units)",
    description: "Mount motorized curtain system",
    stakeholder: "INSTALLER",
    status: "DONE",
    priority: "MEDIUM",
    createdFrom: "TEMPLATE",
    createdAt: twoDaysAgo,
    updatedAt: yesterday,
    roleCategory: "INSTALLER",
    roomId: "room-2",
  },
  {
    id: "inst-task-004",
    projectId: "proj-001",
    title: "Install in-ceiling speakers (2 units)",
    description: "Mount and wire ceiling speakers",
    stakeholder: "INSTALLER",
    status: "NOT_STARTED",
    priority: "MEDIUM",
    createdFrom: "TEMPLATE",
    createdAt: yesterday,
    updatedAt: yesterday,
    roleCategory: "INSTALLER",
    roomId: "room-2",
  },
  // Home Theater tasks
  {
    id: "inst-task-005",
    projectId: "proj-001",
    title: "Install projector",
    description: "Mount projector and connect video/power cables",
    stakeholder: "INSTALLER",
    status: "IN_PROGRESS",
    priority: "HIGH",
    createdFrom: "TEMPLATE",
    createdAt: twoDaysAgo,
    updatedAt: now,
    roleCategory: "INSTALLER",
    roomId: "room-6",
    flagged: true,
    flagReason: "Ceiling mount kit delayed",
  },
  {
    id: "inst-task-006",
    projectId: "proj-001",
    title: "Install AVR 7.2 Channel",
    description: "Rack mount AVR and connect all audio/video sources",
    stakeholder: "INSTALLER",
    status: "NOT_STARTED",
    priority: "HIGH",
    createdFrom: "TEMPLATE",
    createdAt: yesterday,
    updatedAt: yesterday,
    roleCategory: "INSTALLER",
    roomId: "room-6",
  },
  {
    id: "inst-task-007",
    projectId: "proj-001",
    title: "Install 5.1 speaker system",
    description: "Mount all speakers for surround sound",
    stakeholder: "INSTALLER",
    status: "NOT_STARTED",
    priority: "HIGH",
    createdFrom: "TEMPLATE",
    createdAt: yesterday,
    updatedAt: yesterday,
    roleCategory: "INSTALLER",
    roomId: "room-6",
  },
  // Foyer tasks
  {
    id: "inst-task-008",
    projectId: "proj-001",
    title: "Install video doorbell",
    description: "Mount and wire smart doorbell",
    stakeholder: "INSTALLER",
    status: "DONE",
    priority: "MEDIUM",
    createdFrom: "TEMPLATE",
    createdAt: twoDaysAgo,
    updatedAt: twoDaysAgo,
    roleCategory: "INSTALLER",
    roomId: "room-7",
  },
  // General tasks
  {
    id: "inst-task-009",
    projectId: "proj-001",
    title: "Install network switch in server rack",
    description: "Rack mount 24-port PoE switch",
    stakeholder: "INSTALLER",
    status: "DONE",
    priority: "HIGH",
    createdFrom: "TEMPLATE",
    createdAt: twoDaysAgo,
    updatedAt: yesterday,
    roleCategory: "INSTALLER",
    isGeneralTask: true,
  },
  {
    id: "inst-task-010",
    projectId: "proj-001",
    title: "Install NVR for CCTV system",
    description: "Setup NVR and configure storage",
    stakeholder: "INSTALLER",
    status: "IN_PROGRESS",
    priority: "HIGH",
    createdFrom: "TEMPLATE",
    createdAt: yesterday,
    updatedAt: now,
    roleCategory: "INSTALLER",
    isGeneralTask: true,
  },
  // Hygiene tasks
  {
    id: "inst-task-011",
    projectId: "proj-001",
    title: "Clean and organize cable runs",
    description: "Dress all exposed cables neatly",
    stakeholder: "INSTALLER",
    status: "NOT_STARTED",
    priority: "LOW",
    createdFrom: "MANUAL",
    createdAt: now,
    updatedAt: now,
    roleCategory: "INSTALLER",
    isHygieneTask: true,
  },
  {
    id: "inst-task-012",
    projectId: "proj-001",
    title: "Label all network ports",
    description: "Apply labels to all patch panel and wall ports",
    stakeholder: "INSTALLER",
    status: "NOT_STARTED",
    priority: "LOW",
    createdFrom: "MANUAL",
    createdAt: now,
    updatedAt: now,
    roleCategory: "INSTALLER",
    isHygieneTask: true,
  },
];

// Programmer Tasks - Derived from BOQ
export const MOCK_PROGRAMMER_TASKS: RoleBasedTask[] = [
  // Living Room
  {
    id: "prog-task-001",
    projectId: "proj-001",
    title: "Program keypad scenes - Living Room",
    description: "Configure 4-button keypad with preset scenes",
    stakeholder: "PROGRAMMER",
    status: "IN_PROGRESS",
    priority: "HIGH",
    createdFrom: "TEMPLATE",
    createdAt: yesterday,
    updatedAt: now,
    roleCategory: "PROGRAMMER",
    roomId: "room-1",
  },
  {
    id: "prog-task-002",
    projectId: "proj-001",
    title: "Integrate lighting with automation",
    description: "Add DALI lights to control system",
    stakeholder: "PROGRAMMER",
    status: "NOT_STARTED",
    priority: "MEDIUM",
    createdFrom: "TEMPLATE",
    createdAt: yesterday,
    updatedAt: yesterday,
    roleCategory: "PROGRAMMER",
    roomId: "room-1",
  },
  // Master Bedroom
  {
    id: "prog-task-003",
    projectId: "proj-001",
    title: "Program curtain limits",
    description: "Set open/close limits and calibrate motor",
    stakeholder: "PROGRAMMER",
    status: "DONE",
    priority: "MEDIUM",
    createdFrom: "TEMPLATE",
    createdAt: twoDaysAgo,
    updatedAt: yesterday,
    roleCategory: "PROGRAMMER",
    roomId: "room-2",
  },
  {
    id: "prog-task-004",
    projectId: "proj-001",
    title: "Program keypad scenes - Master Bedroom",
    description: "Configure bedside keypad with sleep/wake scenes",
    stakeholder: "PROGRAMMER",
    status: "NOT_STARTED",
    priority: "HIGH",
    createdFrom: "TEMPLATE",
    createdAt: yesterday,
    updatedAt: yesterday,
    roleCategory: "PROGRAMMER",
    roomId: "room-2",
  },
  // Home Theater
  {
    id: "prog-task-005",
    projectId: "proj-001",
    title: "Program touch panel interface",
    description: "Configure UI, scenes, and control logic for theater",
    stakeholder: "PROGRAMMER",
    status: "BLOCKED",
    priority: "HIGH",
    createdFrom: "TEMPLATE",
    createdAt: twoDaysAgo,
    updatedAt: now,
    roleCategory: "PROGRAMMER",
    roomId: "room-6",
    flagged: true,
    flagReason: "Waiting for AVR installation",
  },
  {
    id: "prog-task-006",
    projectId: "proj-001",
    title: "Program AV macro sequences",
    description: "Create movie, music, and gaming macros",
    stakeholder: "PROGRAMMER",
    status: "NOT_STARTED",
    priority: "HIGH",
    createdFrom: "TEMPLATE",
    createdAt: yesterday,
    updatedAt: yesterday,
    roleCategory: "PROGRAMMER",
    roomId: "room-6",
  },
  // Kitchen
  {
    id: "prog-task-007",
    projectId: "proj-001",
    title: "Program lighting scenes - Kitchen",
    description: "Configure cooking, dining, and ambient scenes",
    stakeholder: "PROGRAMMER",
    status: "NOT_STARTED",
    priority: "MEDIUM",
    createdFrom: "TEMPLATE",
    createdAt: now,
    updatedAt: now,
    roleCategory: "PROGRAMMER",
    roomId: "room-4",
  },
  // General Tasks
  {
    id: "prog-task-008",
    projectId: "proj-001",
    title: "Configure central automation controller",
    description: "Setup main processor and network settings",
    stakeholder: "PROGRAMMER",
    status: "DONE",
    priority: "HIGH",
    createdFrom: "TEMPLATE",
    createdAt: twoDaysAgo,
    updatedAt: twoDaysAgo,
    roleCategory: "PROGRAMMER",
    isGeneralTask: true,
  },
  {
    id: "prog-task-009",
    projectId: "proj-001",
    title: "Setup remote access",
    description: "Configure cloud connectivity for remote control",
    stakeholder: "PROGRAMMER",
    status: "IN_PROGRESS",
    priority: "MEDIUM",
    createdFrom: "TEMPLATE",
    createdAt: yesterday,
    updatedAt: now,
    roleCategory: "PROGRAMMER",
    isGeneralTask: true,
  },
  // Hygiene Tasks
  {
    id: "prog-task-010",
    projectId: "proj-001",
    title: "Document all IP addresses",
    description: "Create network documentation spreadsheet",
    stakeholder: "PROGRAMMER",
    status: "NOT_STARTED",
    priority: "LOW",
    createdFrom: "MANUAL",
    createdAt: now,
    updatedAt: now,
    roleCategory: "PROGRAMMER",
    isHygieneTask: true,
  },
  {
    id: "prog-task-011",
    projectId: "proj-001",
    title: "Backup system configuration",
    description: "Export and save all programming files",
    stakeholder: "PROGRAMMER",
    status: "NOT_STARTED",
    priority: "MEDIUM",
    createdFrom: "MANUAL",
    createdAt: now,
    updatedAt: now,
    roleCategory: "PROGRAMMER",
    isHygieneTask: true,
  },
];

// QC Tasks - Derived from BOQ
export const MOCK_QC_TASKS: RoleBasedTask[] = [
  // Living Room
  {
    id: "qc-task-001",
    projectId: "proj-001",
    title: "QC - Test keypad scenes",
    description: "Verify all keypad buttons trigger correct scenes",
    stakeholder: "QC",
    status: "NOT_STARTED",
    priority: "HIGH",
    createdFrom: "TEMPLATE",
    createdAt: now,
    updatedAt: now,
    roleCategory: "QC",
    roomId: "room-1",
  },
  {
    id: "qc-task-002",
    projectId: "proj-001",
    title: "QC - Check speaker audio quality",
    description: "Test frequency response and balance",
    stakeholder: "QC",
    status: "NOT_STARTED",
    priority: "MEDIUM",
    createdFrom: "TEMPLATE",
    createdAt: now,
    updatedAt: now,
    roleCategory: "QC",
    roomId: "room-1",
  },
  // Master Bedroom
  {
    id: "qc-task-003",
    projectId: "proj-001",
    title: "QC - Test curtain operation",
    description: "Verify smooth operation and limit settings",
    stakeholder: "QC",
    status: "IN_PROGRESS",
    priority: "MEDIUM",
    createdFrom: "TEMPLATE",
    createdAt: yesterday,
    updatedAt: now,
    roleCategory: "QC",
    roomId: "room-2",
  },
  {
    id: "qc-task-004",
    projectId: "proj-001",
    title: "QC - Check keypad alignment",
    description: "Verify keypad is level and properly mounted",
    stakeholder: "QC",
    status: "DONE",
    priority: "MEDIUM",
    createdFrom: "TEMPLATE",
    createdAt: twoDaysAgo,
    updatedAt: yesterday,
    roleCategory: "QC",
    roomId: "room-2",
  },
  // Home Theater
  {
    id: "qc-task-005",
    projectId: "proj-001",
    title: "QC - Test AV system",
    description: "Verify audio/video quality and surround sound",
    stakeholder: "QC",
    status: "NOT_STARTED",
    priority: "HIGH",
    createdFrom: "TEMPLATE",
    createdAt: now,
    updatedAt: now,
    roleCategory: "QC",
    roomId: "room-6",
  },
  {
    id: "qc-task-006",
    projectId: "proj-001",
    title: "QC - Calibrate projector",
    description: "Adjust focus, keystone, and color settings",
    stakeholder: "QC",
    status: "NOT_STARTED",
    priority: "HIGH",
    createdFrom: "TEMPLATE",
    createdAt: now,
    updatedAt: now,
    roleCategory: "QC",
    roomId: "room-6",
  },
  // Foyer
  {
    id: "qc-task-007",
    projectId: "proj-001",
    title: "QC - Test video doorbell",
    description: "Check video quality, audio, and notifications",
    stakeholder: "QC",
    status: "DONE",
    priority: "HIGH",
    createdFrom: "TEMPLATE",
    createdAt: yesterday,
    updatedAt: yesterday,
    roleCategory: "QC",
    roomId: "room-7",
  },
  // General Tasks
  {
    id: "qc-task-008",
    projectId: "proj-001",
    title: "QC - Test network connectivity",
    description: "Verify network speeds and coverage throughout",
    stakeholder: "QC",
    status: "IN_PROGRESS",
    priority: "HIGH",
    createdFrom: "TEMPLATE",
    createdAt: yesterday,
    updatedAt: now,
    roleCategory: "QC",
    isGeneralTask: true,
  },
  {
    id: "qc-task-009",
    projectId: "proj-001",
    title: "QC - Verify CCTV recording",
    description: "Check all cameras recording properly",
    stakeholder: "QC",
    status: "NOT_STARTED",
    priority: "HIGH",
    createdFrom: "TEMPLATE",
    createdAt: now,
    updatedAt: now,
    roleCategory: "QC",
    isGeneralTask: true,
  },
  // Hygiene Tasks
  {
    id: "qc-task-010",
    projectId: "proj-001",
    title: "QC - Check cable management",
    description: "Inspect all visible cable runs for neatness",
    stakeholder: "QC",
    status: "NOT_STARTED",
    priority: "LOW",
    createdFrom: "MANUAL",
    createdAt: now,
    updatedAt: now,
    roleCategory: "QC",
    isHygieneTask: true,
  },
  {
    id: "qc-task-011",
    projectId: "proj-001",
    title: "QC - Verify all labels present",
    description: "Check labeling on all ports and equipment",
    stakeholder: "QC",
    status: "NOT_STARTED",
    priority: "LOW",
    createdFrom: "MANUAL",
    createdAt: now,
    updatedAt: now,
    roleCategory: "QC",
    isHygieneTask: true,
  },
];

// Helper for generating timestamps
const threeDaysAgo = new Date(Date.now() - 259200000).toISOString();
const fourDaysAgo = new Date(Date.now() - 345600000).toISOString();
const fiveDaysAgo = new Date(Date.now() - 432000000).toISOString();
const oneHourAgo = new Date(Date.now() - 3600000).toISOString();
const threeHoursAgo = new Date(Date.now() - 10800000).toISOString();
const sixHoursAgo = new Date(Date.now() - 21600000).toISOString();

// Activity log mock data - Comprehensive for all tasks
export const MOCK_TASK_ACTIVITIES: TaskActivity[] = [
  // PM Task 001 - Get electrical layout approval
  {
    id: "act-001",
    taskId: "pm-task-001",
    type: "CREATED",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: fiveDaysAgo,
    details: "Task created",
  },
  {
    id: "act-002",
    taskId: "pm-task-001",
    type: "DEPENDENCY_MARKED",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: fourDaysAgo,
    details: "Marked as Architect Dependency",
    metadata: {
      dependencyType: "ARCHITECT",
    },
  },
  {
    id: "act-003",
    taskId: "pm-task-001",
    type: "STATUS_CHANGE",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: twoDaysAgo,
    details: "Status changed from Not Started to In Progress",
    metadata: {
      oldStatus: "NOT_STARTED",
      newStatus: "IN_PROGRESS",
    },
  },
  {
    id: "act-004",
    taskId: "pm-task-001",
    type: "COMMENT_ADDED",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: yesterday,
    details: "Sent follow-up email to architect team",
  },

  // PM Task 002 - Client approval for AV
  {
    id: "act-005",
    taskId: "pm-task-002",
    type: "CREATED",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: threeDaysAgo,
    details: "Task created",
  },
  {
    id: "act-006",
    taskId: "pm-task-002",
    type: "DEPENDENCY_MARKED",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: threeDaysAgo,
    details: "Marked as Client Dependency",
    metadata: {
      dependencyType: "CLIENT",
    },
  },

  // PM Task 003 - HVAC coordination (Blocked)
  {
    id: "act-007",
    taskId: "pm-task-003",
    type: "CREATED",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: fiveDaysAgo,
    details: "Task created",
  },
  {
    id: "act-008",
    taskId: "pm-task-003",
    type: "DEPENDENCY_MARKED",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: fourDaysAgo,
    details: "Marked as Third Party Dependency",
    metadata: {
      dependencyType: "THIRD_PARTY",
    },
  },
  {
    id: "act-009",
    taskId: "pm-task-003",
    type: "STATUS_CHANGE",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: yesterday,
    details: "Status changed from In Progress to Blocked",
    metadata: {
      oldStatus: "IN_PROGRESS",
      newStatus: "BLOCKED",
    },
  },
  {
    id: "act-010",
    taskId: "pm-task-003",
    type: "FLAG_ADDED",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: sixHoursAgo,
    details: "Task flagged as critical",
    metadata: {
      flagReason: "Critical path impact",
    },
  },

  // PM Task 004 - Cat6 cables (Done)
  {
    id: "act-011",
    taskId: "pm-task-004",
    type: "CREATED",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: fourDaysAgo,
    details: "Task created",
  },
  {
    id: "act-012",
    taskId: "pm-task-004",
    type: "STATUS_CHANGE",
    userId: "user-004",
    userName: "Priya Sharma",
    timestamp: twoDaysAgo,
    details: "Status changed from Not Started to In Progress",
    metadata: {
      oldStatus: "NOT_STARTED",
      newStatus: "IN_PROGRESS",
    },
  },
  {
    id: "act-013",
    taskId: "pm-task-004",
    type: "STATUS_CHANGE",
    userId: "user-004",
    userName: "Priya Sharma",
    timestamp: yesterday,
    details: "Status changed from In Progress to Done",
    metadata: {
      oldStatus: "IN_PROGRESS",
      newStatus: "DONE",
    },
  },

  // Installer Task 001 - Ceiling speakers (Living Room)
  {
    id: "act-014",
    taskId: "inst-task-001",
    type: "CREATED",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: fourDaysAgo,
    details: "Task auto-generated from BOQ",
  },
  {
    id: "act-015",
    taskId: "inst-task-001",
    type: "ASSIGNED",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: threeDaysAgo,
    details: "Assigned to Amit Singh",
  },
  {
    id: "act-016",
    taskId: "inst-task-001",
    type: "STATUS_CHANGE",
    userId: "user-002",
    userName: "Amit Singh",
    timestamp: twoDaysAgo,
    details: "Status changed from Not Started to In Progress",
    metadata: {
      oldStatus: "NOT_STARTED",
      newStatus: "IN_PROGRESS",
    },
  },
  {
    id: "act-017",
    taskId: "inst-task-001",
    type: "IMAGE_UPLOAD",
    userId: "user-002",
    userName: "Amit Singh",
    timestamp: yesterday,
    details: "Uploaded progress photo - first speaker mounted",
  },

  // Installer Task 003 - Curtain motors (Done)
  {
    id: "act-018",
    taskId: "inst-task-003",
    type: "CREATED",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: fiveDaysAgo,
    details: "Task auto-generated from BOQ",
  },
  {
    id: "act-019",
    taskId: "inst-task-003",
    type: "STATUS_CHANGE",
    userId: "user-002",
    userName: "Amit Singh",
    timestamp: threeDaysAgo,
    details: "Status changed from Not Started to In Progress",
    metadata: {
      oldStatus: "NOT_STARTED",
      newStatus: "IN_PROGRESS",
    },
  },
  {
    id: "act-020",
    taskId: "inst-task-003",
    type: "STATUS_CHANGE",
    userId: "user-002",
    userName: "Amit Singh",
    timestamp: yesterday,
    details: "Status changed from In Progress to Done",
    metadata: {
      oldStatus: "IN_PROGRESS",
      newStatus: "DONE",
    },
  },
  {
    id: "act-021",
    taskId: "inst-task-003",
    type: "IMAGE_UPLOAD",
    userId: "user-002",
    userName: "Amit Singh",
    timestamp: yesterday,
    details: "Uploaded completion photo",
  },

  // Installer Task 005 - Projector (Flagged)
  {
    id: "act-022",
    taskId: "inst-task-005",
    type: "CREATED",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: fourDaysAgo,
    details: "Task auto-generated from BOQ",
  },
  {
    id: "act-023",
    taskId: "inst-task-005",
    type: "STATUS_CHANGE",
    userId: "user-002",
    userName: "Amit Singh",
    timestamp: twoDaysAgo,
    details: "Status changed from Not Started to In Progress",
    metadata: {
      oldStatus: "NOT_STARTED",
      newStatus: "IN_PROGRESS",
    },
  },
  {
    id: "act-024",
    taskId: "inst-task-005",
    type: "FLAG_ADDED",
    userId: "user-002",
    userName: "Amit Singh",
    timestamp: threeHoursAgo,
    details: "Task flagged due to delay",
    metadata: {
      flagReason: "Ceiling mount kit delayed",
    },
  },

  // Programmer Task 001 - Keypad scenes (Living Room)
  {
    id: "act-025",
    taskId: "prog-task-001",
    type: "CREATED",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: threeDaysAgo,
    details: "Task auto-generated from BOQ",
  },
  {
    id: "act-026",
    taskId: "prog-task-001",
    type: "STATUS_CHANGE",
    userId: "user-003",
    userName: "Vikram Patel",
    timestamp: yesterday,
    details: "Status changed from Not Started to In Progress",
    metadata: {
      oldStatus: "NOT_STARTED",
      newStatus: "IN_PROGRESS",
    },
  },
  {
    id: "act-027",
    taskId: "prog-task-001",
    type: "COMMENT_ADDED",
    userId: "user-003",
    userName: "Vikram Patel",
    timestamp: oneHourAgo,
    details: "Scene 1 and 2 configured, working on Scene 3",
  },

  // Programmer Task 003 - Curtain limits (Done)
  {
    id: "act-028",
    taskId: "prog-task-003",
    type: "CREATED",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: fourDaysAgo,
    details: "Task auto-generated from BOQ",
  },
  {
    id: "act-029",
    taskId: "prog-task-003",
    type: "STATUS_CHANGE",
    userId: "user-003",
    userName: "Vikram Patel",
    timestamp: twoDaysAgo,
    details: "Status changed from Not Started to In Progress",
    metadata: {
      oldStatus: "NOT_STARTED",
      newStatus: "IN_PROGRESS",
    },
  },
  {
    id: "act-030",
    taskId: "prog-task-003",
    type: "STATUS_CHANGE",
    userId: "user-003",
    userName: "Vikram Patel",
    timestamp: yesterday,
    details: "Status changed from In Progress to Done",
    metadata: {
      oldStatus: "IN_PROGRESS",
      newStatus: "DONE",
    },
  },

  // Programmer Task 005 - Touch panel (Blocked)
  {
    id: "act-031",
    taskId: "prog-task-005",
    type: "CREATED",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: fourDaysAgo,
    details: "Task auto-generated from BOQ",
  },
  {
    id: "act-032",
    taskId: "prog-task-005",
    type: "STATUS_CHANGE",
    userId: "user-003",
    userName: "Vikram Patel",
    timestamp: twoDaysAgo,
    details: "Status changed from Not Started to Blocked",
    metadata: {
      oldStatus: "NOT_STARTED",
      newStatus: "BLOCKED",
    },
  },
  {
    id: "act-033",
    taskId: "prog-task-005",
    type: "DEPENDENCY_MARKED",
    userId: "user-003",
    userName: "Vikram Patel",
    timestamp: twoDaysAgo,
    details: "Marked as blocked - waiting for AVR installation",
    metadata: {
      flagReason: "Waiting for AVR installation",
    },
  },
  {
    id: "act-034",
    taskId: "prog-task-005",
    type: "FLAG_ADDED",
    userId: "user-003",
    userName: "Vikram Patel",
    timestamp: yesterday,
    details: "Task flagged",
    metadata: {
      flagReason: "Waiting for AVR installation",
    },
  },

  // Programmer Task 008 - Central controller (Done)
  {
    id: "act-035",
    taskId: "prog-task-008",
    type: "CREATED",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: fiveDaysAgo,
    details: "Task auto-generated from BOQ",
  },
  {
    id: "act-036",
    taskId: "prog-task-008",
    type: "STATUS_CHANGE",
    userId: "user-003",
    userName: "Vikram Patel",
    timestamp: fourDaysAgo,
    details: "Status changed from Not Started to In Progress",
    metadata: {
      oldStatus: "NOT_STARTED",
      newStatus: "IN_PROGRESS",
    },
  },
  {
    id: "act-037",
    taskId: "prog-task-008",
    type: "STATUS_CHANGE",
    userId: "user-003",
    userName: "Vikram Patel",
    timestamp: threeDaysAgo,
    details: "Status changed from In Progress to Done",
    metadata: {
      oldStatus: "IN_PROGRESS",
      newStatus: "DONE",
    },
  },

  // QC Task 003 - Curtain operation (In Progress)
  {
    id: "act-038",
    taskId: "qc-task-003",
    type: "CREATED",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: twoDaysAgo,
    details: "Task auto-generated from BOQ",
  },
  {
    id: "act-039",
    taskId: "qc-task-003",
    type: "STATUS_CHANGE",
    userId: "user-005",
    userName: "Suresh Menon",
    timestamp: yesterday,
    details: "Status changed from Not Started to In Progress",
    metadata: {
      oldStatus: "NOT_STARTED",
      newStatus: "IN_PROGRESS",
    },
  },
  {
    id: "act-040",
    taskId: "qc-task-003",
    type: "COMMENT_ADDED",
    userId: "user-005",
    userName: "Suresh Menon",
    timestamp: threeHoursAgo,
    details: "Testing motor 1, smooth operation confirmed",
  },

  // QC Task 004 - Keypad alignment (Done)
  {
    id: "act-041",
    taskId: "qc-task-004",
    type: "CREATED",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: threeDaysAgo,
    details: "Task auto-generated from BOQ",
  },
  {
    id: "act-042",
    taskId: "qc-task-004",
    type: "STATUS_CHANGE",
    userId: "user-005",
    userName: "Suresh Menon",
    timestamp: twoDaysAgo,
    details: "Status changed from Not Started to In Progress",
    metadata: {
      oldStatus: "NOT_STARTED",
      newStatus: "IN_PROGRESS",
    },
  },
  {
    id: "act-043",
    taskId: "qc-task-004",
    type: "IMAGE_UPLOAD",
    userId: "user-005",
    userName: "Suresh Menon",
    timestamp: yesterday,
    details: "Uploaded alignment verification photo",
  },
  {
    id: "act-044",
    taskId: "qc-task-004",
    type: "STATUS_CHANGE",
    userId: "user-005",
    userName: "Suresh Menon",
    timestamp: yesterday,
    details: "Status changed from In Progress to Done",
    metadata: {
      oldStatus: "IN_PROGRESS",
      newStatus: "DONE",
    },
  },

  // QC Task 007 - Video doorbell (Done)
  {
    id: "act-045",
    taskId: "qc-task-007",
    type: "CREATED",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: twoDaysAgo,
    details: "Task auto-generated from BOQ",
  },
  {
    id: "act-046",
    taskId: "qc-task-007",
    type: "STATUS_CHANGE",
    userId: "user-005",
    userName: "Suresh Menon",
    timestamp: yesterday,
    details: "Status changed from Not Started to In Progress",
    metadata: {
      oldStatus: "NOT_STARTED",
      newStatus: "IN_PROGRESS",
    },
  },
  {
    id: "act-047",
    taskId: "qc-task-007",
    type: "STATUS_CHANGE",
    userId: "user-005",
    userName: "Suresh Menon",
    timestamp: yesterday,
    details: "Status changed from In Progress to Done",
    metadata: {
      oldStatus: "IN_PROGRESS",
      newStatus: "DONE",
    },
  },
  {
    id: "act-048",
    taskId: "qc-task-007",
    type: "IMAGE_UPLOAD",
    userId: "user-005",
    userName: "Suresh Menon",
    timestamp: yesterday,
    details: "Uploaded test screenshot showing video feed",
  },

  // QC Task 008 - Network connectivity (In Progress)
  {
    id: "act-049",
    taskId: "qc-task-008",
    type: "CREATED",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: twoDaysAgo,
    details: "Task auto-generated from BOQ",
  },
  {
    id: "act-050",
    taskId: "qc-task-008",
    type: "STATUS_CHANGE",
    userId: "user-005",
    userName: "Suresh Menon",
    timestamp: yesterday,
    details: "Status changed from Not Started to In Progress",
    metadata: {
      oldStatus: "NOT_STARTED",
      newStatus: "IN_PROGRESS",
    },
  },
  {
    id: "act-051",
    taskId: "qc-task-008",
    type: "COMMENT_ADDED",
    userId: "user-005",
    userName: "Suresh Menon",
    timestamp: sixHoursAgo,
    details: "Living room and bedroom tested - speeds OK",
  },
  {
    id: "act-052",
    taskId: "qc-task-008",
    type: "COMMENT_ADDED",
    userId: "user-005",
    userName: "Suresh Menon",
    timestamp: oneHourAgo,
    details: "Kitchen and dining area testing in progress",
  },

  // Installer Task 008 - Video doorbell (Done)
  {
    id: "act-053",
    taskId: "inst-task-008",
    type: "CREATED",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: fourDaysAgo,
    details: "Task auto-generated from BOQ",
  },
  {
    id: "act-054",
    taskId: "inst-task-008",
    type: "STATUS_CHANGE",
    userId: "user-002",
    userName: "Amit Singh",
    timestamp: threeDaysAgo,
    details: "Status changed from Not Started to In Progress",
    metadata: {
      oldStatus: "NOT_STARTED",
      newStatus: "IN_PROGRESS",
    },
  },
  {
    id: "act-055",
    taskId: "inst-task-008",
    type: "STATUS_CHANGE",
    userId: "user-002",
    userName: "Amit Singh",
    timestamp: threeDaysAgo,
    details: "Status changed from In Progress to Done",
    metadata: {
      oldStatus: "IN_PROGRESS",
      newStatus: "DONE",
    },
  },

  // Installer Task 009 - Network switch (Done)
  {
    id: "act-056",
    taskId: "inst-task-009",
    type: "CREATED",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: fiveDaysAgo,
    details: "Task auto-generated from BOQ",
  },
  {
    id: "act-057",
    taskId: "inst-task-009",
    type: "STATUS_CHANGE",
    userId: "user-002",
    userName: "Amit Singh",
    timestamp: fourDaysAgo,
    details: "Status changed from Not Started to In Progress",
    metadata: {
      oldStatus: "NOT_STARTED",
      newStatus: "IN_PROGRESS",
    },
  },
  {
    id: "act-058",
    taskId: "inst-task-009",
    type: "STATUS_CHANGE",
    userId: "user-002",
    userName: "Amit Singh",
    timestamp: threeDaysAgo,
    details: "Status changed from In Progress to Done",
    metadata: {
      oldStatus: "IN_PROGRESS",
      newStatus: "DONE",
    },
  },
  {
    id: "act-059",
    taskId: "inst-task-009",
    type: "IMAGE_UPLOAD",
    userId: "user-002",
    userName: "Amit Singh",
    timestamp: threeDaysAgo,
    details: "Uploaded rack installation photo",
  },

  // Installer Task 010 - NVR (In Progress)
  {
    id: "act-060",
    taskId: "inst-task-010",
    type: "CREATED",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: threeDaysAgo,
    details: "Task auto-generated from BOQ",
  },
  {
    id: "act-061",
    taskId: "inst-task-010",
    type: "STATUS_CHANGE",
    userId: "user-002",
    userName: "Amit Singh",
    timestamp: yesterday,
    details: "Status changed from Not Started to In Progress",
    metadata: {
      oldStatus: "NOT_STARTED",
      newStatus: "IN_PROGRESS",
    },
  },
  {
    id: "act-062",
    taskId: "inst-task-010",
    type: "COMMENT_ADDED",
    userId: "user-002",
    userName: "Amit Singh",
    timestamp: oneHourAgo,
    details: "NVR mounted, configuring storage drives",
  },

  // PM Task 006 - Lighting scene requirements
  {
    id: "act-063",
    taskId: "pm-task-006",
    type: "CREATED",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: threeDaysAgo,
    details: "Task created",
  },
  {
    id: "act-064",
    taskId: "pm-task-006",
    type: "STATUS_CHANGE",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: yesterday,
    details: "Status changed from Not Started to In Progress",
    metadata: {
      oldStatus: "NOT_STARTED",
      newStatus: "IN_PROGRESS",
    },
  },

  // PM Task 008 - Client automation sign-off
  {
    id: "act-065",
    taskId: "pm-task-008",
    type: "CREATED",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: fourDaysAgo,
    details: "Task created",
  },
  {
    id: "act-066",
    taskId: "pm-task-008",
    type: "DEPENDENCY_MARKED",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: fourDaysAgo,
    details: "Marked as Client Dependency",
    metadata: {
      dependencyType: "CLIENT",
    },
  },
  {
    id: "act-067",
    taskId: "pm-task-008",
    type: "STATUS_CHANGE",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: twoDaysAgo,
    details: "Status changed from Not Started to In Progress",
    metadata: {
      oldStatus: "NOT_STARTED",
      newStatus: "IN_PROGRESS",
    },
  },
  {
    id: "act-068",
    taskId: "pm-task-008",
    type: "COMMENT_ADDED",
    userId: "user-001",
    userName: "Rajesh Kumar",
    timestamp: yesterday,
    details: "Site visit scheduled for Thursday",
  },
];

// Helper function to group tasks by room
export function groupTasksByRoom(tasks: RoleBasedTask[]): {
  roomGroups: TaskRoomGroup[];
  generalGroup: SpecialTaskGroup;
  hygieneGroup: SpecialTaskGroup;
} {
  const roomMap = new Map<string, RoleBasedTask[]>();
  const generalTasks: RoleBasedTask[] = [];
  const hygieneTasks: RoleBasedTask[] = [];

  tasks.forEach((task) => {
    if (task.isHygieneTask) {
      hygieneTasks.push(task);
    } else if (task.isGeneralTask || !task.roomId) {
      generalTasks.push(task);
    } else {
      const existing = roomMap.get(task.roomId) || [];
      existing.push(task);
      roomMap.set(task.roomId, existing);
    }
  });

  const roomGroups: TaskRoomGroup[] = [];
  MOCK_TASK_ROOMS.forEach((room) => {
    const roomTasks = roomMap.get(room.id);
    if (roomTasks && roomTasks.length > 0) {
      roomGroups.push({
        roomId: room.id,
        roomName: room.name,
        tasks: roomTasks,
        isExpanded: true,
      });
    }
  });

  return {
    roomGroups,
    generalGroup: {
      id: "general",
      name: "General Tasks",
      tasks: generalTasks,
      isExpanded: true,
    },
    hygieneGroup: {
      id: "hygiene",
      name: "Hygiene Tasks",
      tasks: hygieneTasks,
      isExpanded: true,
    },
  };
}

// Helper to get activities for a task
export function getTaskActivities(taskId: string): TaskActivity[] {
  return MOCK_TASK_ACTIVITIES.filter((a) => a.taskId === taskId).sort(
    (a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()
  );
}

// Helper to calculate task stats
export function calculateTaskStats(tasks: RoleBasedTask[]) {
  return {
    total: tasks.length,
    notStarted: tasks.filter((t) => t.status === "NOT_STARTED").length,
    inProgress: tasks.filter((t) => t.status === "IN_PROGRESS").length,
    blocked: tasks.filter((t) => t.status === "BLOCKED").length,
    done: tasks.filter((t) => t.status === "DONE").length,
  };
}
