import type { Project } from "../types";

// Mock project data that matches what we have in the projects table
export const MOCK_PROJECTS: Project[] = [
  {
    id: "proj-001",
    name: "Skyline Tower Upgrade",
    code: "PRJ-2401",
    clientName: "Skyline Properties",
    location: "Mumbai, MH",
    stage: "Execution",
    health: "Good",
    targetHandoverDate: "March 15, 2026",
    assignedSupervisor: "Rajesh Kumar",
  },
  {
    id: "proj-002",
    name: "Greenfield Residential Phase A",
    code: "PRJ-2402",
    clientName: "Greenfield Developers",
    location: "Pune, MH",
    stage: "QC",
    health: "At Risk",
    targetHandoverDate: "February 28, 2026",
    assignedSupervisor: "Priya Sharma",
  },
  {
    id: "proj-003",
    name: "Northbridge Hub",
    code: "PRJ-2403",
    clientName: "Northbridge Ventures",
    location: "Bengaluru, KA",
    stage: "Design",
    health: "Good",
    targetHandoverDate: "May 20, 2026",
    assignedSupervisor: "Amit Patel",
  },
  {
    id: "proj-004",
    name: "Harbor Point",
    code: "PRJ-2404",
    clientName: "Harbor Realty",
    location: "Chennai, TN",
    stage: "Audit",
    health: "Critical",
    targetHandoverDate: "January 31, 2026",
    assignedSupervisor: "Meera Iyer",
  },
  {
    id: "proj-005",
    name: "Riverside Villas",
    code: "PRJ-2405",
    clientName: "Riverside Holdings",
    location: "Hyderabad, TS",
    stage: "Execution",
    health: "Good",
    targetHandoverDate: "April 10, 2026",
    assignedSupervisor: "Suresh Reddy",
  },
  {
    id: "proj-006",
    name: "Central Park Extension",
    code: "PRJ-2406",
    clientName: "Central Park Ltd",
    location: "Delhi, DL",
    stage: "QC",
    health: "Good",
    targetHandoverDate: "March 5, 2026",
    assignedSupervisor: "Anjali Verma",
  },
  {
    id: "proj-007",
    name: "Coastal Heights",
    code: "PRJ-2407",
    clientName: "Coastal Builders",
    location: "Kochi, KL",
    stage: "Execution",
    health: "At Risk",
    targetHandoverDate: "April 25, 2026",
    assignedSupervisor: "Vikram Nair",
  },
  {
    id: "proj-008",
    name: "Urban Residency Block B",
    code: "PRJ-2408",
    clientName: "Urban Homes",
    location: "Ahmedabad, GJ",
    stage: "Design",
    health: "Good",
    targetHandoverDate: "June 1, 2026",
    assignedSupervisor: "Deepa Shah",
  },
];

export function getProjectById(projectId: string): Project | null {
  return MOCK_PROJECTS.find((p) => p.id === projectId) || null;
}
