/**
 * Mock data for Delight Engine
 * Sample events and stickers for frontend development
 */

import type { DelightEvent, AppreciationSticker, TriggerConfig } from "../types";

export const MOCK_DELIGHT_EVENTS: DelightEvent[] = [
  {
    id: "de-001",
    type: "milestone",
    title: "First project milestone reached",
    description: "Completed your first project milestone. The system noticed your consistent delivery.",
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    seen: false,
    iconName: "Target",
  },
  {
    id: "de-002",
    type: "consistency",
    title: "Seven-day completion streak",
    description: "You've completed tasks on schedule for seven consecutive days.",
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    seen: true,
    iconName: "CalendarCheck",
  },
  {
    id: "de-003",
    type: "quality",
    title: "Quality review passed on first attempt",
    description: "Task #2341 passed quality review without revisions. Client noted attention to detail.",
    timestamp: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    seen: true,
    iconName: "ShieldCheck",
  },
  {
    id: "de-004",
    type: "learning",
    title: "New skill module completed",
    description: "Finished Advanced Excel training module. Certificate issued.",
    timestamp: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    seen: true,
    iconName: "GraduationCap",
  },
  {
    id: "de-005",
    type: "peer_thanks",
    title: "Recognition from Priya Sharma",
    description: "Priya sent you an appreciation for collaboration on Project Omega.",
    timestamp: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    seen: true,
    iconName: "Heart",
  },
  {
    id: "de-006",
    type: "milestone",
    title: "100 tasks completed",
    description: "Reached a significant milestone. Your work contributes to team velocity.",
    timestamp: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    seen: true,
    iconName: "Award",
  },
  {
    id: "de-007",
    type: "quality",
    title: "Consistent quality score maintained",
    description: "Your last ten deliverables scored above 90% in quality metrics.",
    timestamp: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    seen: true,
    iconName: "TrendingUp",
  },
  {
    id: "de-008",
    type: "consistency",
    title: "No missed deadlines this month",
    description: "All tasks submitted on or before deadline. Strong execution discipline.",
    timestamp: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
    seen: true,
    iconName: "Clock",
  },
  {
    id: "de-009",
    type: "learning",
    title: "First certification earned",
    description: "Completed Data Privacy Compliance certification. Required for client work.",
    timestamp: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString(),
    seen: true,
    iconName: "FileCheck",
  },
  {
    id: "de-010",
    type: "peer_thanks",
    title: "Recognition from Rahul Verma",
    description: "Rahul appreciated your quick turnaround on urgent document review.",
    timestamp: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
    seen: true,
    iconName: "Heart",
  },
];

export const MOCK_APPRECIATION_STICKERS: AppreciationSticker[] = [
  {
    id: "sticker-001",
    fromUserId: "user-102",
    fromUserName: "Priya Sharma",
    toUserId: "user-101",
    message: "Thanks for walking me through the Excel macros. Saved me hours of manual work.",
    variant: "helpful",
    timestamp: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
    context: "project-omega",
    seen: true,
  },
  {
    id: "sticker-002",
    fromUserId: "user-103",
    fromUserName: "Rahul Verma",
    toUserId: "user-101",
    message: "Great turnaround time on the document review. Client was impressed.",
    variant: "great_work",
    timestamp: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
    context: "task-2341",
    seen: true,
  },
  {
    id: "sticker-003",
    fromUserId: "user-104",
    fromUserName: "Anjali Desai",
    toUserId: "user-101",
    message: "Your notes from the client call were thorough and clear. Helped the whole team.",
    variant: "collaboration",
    timestamp: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    context: "project-alpha",
    seen: false,
  },
  {
    id: "sticker-004",
    fromUserId: "user-105",
    fromUserName: "Sanjay Nair",
    toUserId: "user-101",
    message: "Thanks for covering my shift last week. Appreciate it.",
    variant: "thanks",
    timestamp: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    seen: true,
  },
];

export const MOCK_TRIGGER_CONFIGS: TriggerConfig[] = [
  {
    id: "trigger-001",
    type: "task_completion",
    enabled: true,
    description: "Recognize task completion milestones",
    criteria: "Every 10, 50, 100, 250 tasks",
  },
  {
    id: "trigger-002",
    type: "streak",
    enabled: true,
    description: "Acknowledge consistent daily completion",
    criteria: "3, 7, 14, 30 consecutive days",
  },
  {
    id: "trigger-003",
    type: "quality_score",
    enabled: true,
    description: "Celebrate high quality work",
    criteria: "3 consecutive deliverables above 90%",
  },
  {
    id: "trigger-004",
    type: "first_time",
    enabled: true,
    description: "Mark first-time achievements",
    criteria: "First project, first certification, first review pass",
  },
  {
    id: "trigger-005",
    type: "peer_sticker",
    enabled: true,
    description: "Notify when receiving peer appreciation",
    criteria: "Immediate notification",
  },
  {
    id: "trigger-006",
    type: "project_milestone",
    enabled: false,
    description: "Recognize major project milestones",
    criteria: "Project phase completion, client approval",
  },
];
